image: node:latest

cache:
  paths:
    - node_modules/
before_script:
  - npm i -g firebase-tools@11.13.0

deploy-production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install
    - npm run build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
